name: Lint workflow

on: [ pull_request ]

jobs:
  sources:
    name: Sources
    uses: leo-ely/github-workflows/.github/workflows/lint-gradle.yml@main
    permissions:
      contents: read
    with:
      regex_include: .*src/.*
    secrets: inherit
  tests:
    name: Tests
    uses: leo-ely/github-workflows/.github/workflows/lint-gradle.yml@main
    permissions:
      contents: read
    with:
      regex_include: .*test/.*
    secrets: inherit
