name: SAST scan workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codeql:
    name: CodeQL
    uses: leo-ely/github-workflows/.github/workflows/codeql-gradle.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      languages: '["kotlin"]'
    secrets: inherit
